import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { MousePointer } from "@/components/shared";
import { ViewTransitions } from "next-view-transitions";

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${jost.className} bg-background text-3xs relative`}>
          {children}
          <MousePointer />
        </body>
      </html>
    </ViewTransitions>
  );
}
