import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { NavBar, MousePointer } from "@/components/shared";

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} bg-background text-3xs relative`}>
        <NavBar />
         {children}
        <MousePointer />
      </body>
    </html>
  );
}
